# Copyright (c) Tailscale Inc & contributors
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: v2
name: lanhc-operator
description: A Helm chart for Lanhc Kubernetes operator
home: https://github.com/lanhc/lanhc

keywords:
  - "lanhc"
  - "vpn"
  - "ingress"
  - "egress"
  - "wireguard"

sources:
- https://github.com/lanhc/lanhc

type: application

maintainers:
  - name: lanhc-maintainers
    url: https://lanhc.com/

# version will be set to Lanhc repo tag (without 'v') at release time.
version: 0.1.0

# appVersion will be set to Lanhc repo tag at release time.
appVersion: "stable"
