# Copyright (c) Tailscale Inc & contributors
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-apiserver-auth-proxy
  namespace: lanhc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lanhc-auth-proxy
rules:
- apiGroups: [""]
  resources: ["users", "groups"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lanhc-auth-proxy
subjects:
- kind: ServiceAccount
  name: operator
  namespace: lanhc
- kind: ServiceAccount
  name: kube-apiserver-auth-proxy
  namespace: lanhc
roleRef:
  kind: ClusterRole
  name: lanhc-auth-proxy
  apiGroup: rbac.authorization.k8s.io